In [1]:
import sys
import os
import pandas as pd
from langchain_core.messages import SystemMessage

from eval_prompts import *

evals_dir = os.path.abspath(os.path.join(os.getcwd(), '../'))
sys.path.insert(0, evals_dir)

from eval_utils import *  # Import all functions from eval_utils
from src.evaluator import Evaluator
from src.traces_etl import TracesETL

evaluator = Evaluator()
trace_etl = TracesETL()

In [2]:
golden_df = get_golden_dataset()
golden_lod = golden_df.to_dict('records')

✅ Success with encoding: cp1252

In [3]:
factual_accuracy_response_lod, successful_response_response_lod = get_auto_annotations(golden_lod, evaluator)

0.0
0.21
0.43
0.64
0.85

In [4]:
response_lods = [factual_accuracy_response_lod, successful_response_response_lod]
eval_results_df = create_eval_results_df(response_lods, golden_df)
eval_results_df.head()

,response,response_reasoning,eval_name,thread_id,golden_response
0,fail,Remy's response claims there is no specific Gi...,factual_accuracy,0f6927b6-efdb-40ea-9cad-8bdd568564fd,fail
1,fail,Remy's response provides a detailed descriptio...,factual_accuracy,1416f201-ec33-44f4-bef4-33399b79baea,pass
2,fail,Remy's response provides detailed information ...,factual_accuracy,df37d78e-532b-4ed0-a6a9-94cee33a5301,fail
3,fail,Remy's response provides information about Eri...,factual_accuracy,b4ad42d2-6b38-422c-b597-23642e9a366c,fail
4,fail,Remy's response contains detailed information ...,factual_accuracy,be1b94f5-8522-4de6-a942-8d2b80f369e5,pass

In [5]:
eval_results_df.groupby(["eval_name", "response"])["thread_id"].count().reset_index()

           eval_name response  thread_id
0  complete_response     fail          8
1  complete_response     pass         39
2   factual_accuracy     fail         44
3   factual_accuracy     pass          3

In [6]:
eval_results_df["eval_match"] = eval_results_df["golden_response"] == eval_results_df["response"]
eval_results_df.groupby(["eval_name", "eval_match"])["thread_id"].count().reset_index()

           eval_name  eval_match  thread_id
0  complete_response       False          4
1  complete_response        True         43
2   factual_accuracy       False         38
3   factual_accuracy        True          9

In [7]:
final_eval_df = eval_results_df.merge(golden_df[["thread_id", "ai_answer", "system_prompt", "tool_used", "human_question"]], on="thread_id", how="left")
final_eval_df.head()

,response,response_reasoning,eval_name,thread_id,golden_response,eval_match,ai_answer,system_prompt,tool_used,human_question
0,fail,Remy's response claims there is no specific Gi...,factual_accuracy,0f6927b6-efdb-40ea-9cad-8bdd568564fd,fail,True,It seems that there is no specific GitHub acti...,You are a helpful assitant named Remy whose ob...,True,Can you describe what github activity Eric has...
1,fail,Remy's response provides a detailed descriptio...,factual_accuracy,1416f201-ec33-44f4-bef4-33399b79baea,pass,False,The end-to-end tagging product described invol...,You are a helpful assitant named Remy whose ob...,False,Can you describe the architecture of the end-t...
2,fail,Remy's response provides detailed information ...,factual_accuracy,df37d78e-532b-4ed0-a6a9-94cee33a5301,fail,True,The propensity model mentioned in relation to ...,You are a helpful assitant named Remy whose ob...,False,Can you provide more information about the pro...
3,fail,Remy's response provides information about Eri...,factual_accuracy,b4ad42d2-6b38-422c-b597-23642e9a366c,fail,True,It seems there are no specific contributions r...,You are a helpful assitant named Remy whose ob...,True,Can you share what github contributions Eric m...
4,fail,Remy's response contains detailed information ...,factual_accuracy,be1b94f5-8522-4de6-a942-8d2b80f369e5,pass,False,The Two Tower models in the RaaS (Relevancy as...,You are a helpful assitant named Remy whose ob...,False,Can you elaborate on how the Two Tower models ...