%load_ext autoreload
%autoreload 2

In [1]:
import sys
import os
import pandas as pd


evals_dir = os.path.abspath(os.path.join(os.getcwd(), '../'))
sys.path.insert(0, evals_dir)

from eval_utils import * 
from eval_prompts import * # Import all functions from eval_utils
from src.evaluator import Evaluator
from src.traces_etl import TracesETL

evaluator = Evaluator()
trace_etl = TracesETL()

In [2]:
golden_df = get_golden_dataset()
questions = golden_df['human_question'].tolist()

✅ Success with encoding: cp1252

In [3]:
for i, question in enumerate(questions):
    print(round(i / len(questions), 2))
    response = ask_single_question(question)

0.0
0.02
0.04
0.06
0.09
0.11
0.13
0.15
0.17
0.19
0.21
0.23
0.26
0.28
0.3
0.32
0.34
0.36
0.38
0.4
0.43
0.45
0.47
0.49
0.51
0.53
0.55
0.57
0.6
0.62
0.64
0.66
0.68
0.7
0.72
0.74
0.77
0.79
0.81
0.83
0.85
0.87
0.89
0.91
0.94
0.96
0.98

In [5]:
eval_lod = trace_etl.create_eval_lod(is_local_testing=True, lookback_days=1)
eval_df = pd.DataFrame(eval_lod)
print(eval_df.shape)
eval_df.head()

(141, 7)

,thread_id,human_question,system_prompt,ai_answer,tool_used,intent_classification,github_stats_classification
0,c1b3940c-fb32-4799-a7a2-e0c7449413c6,Can you explain how Vespa is utilized in your ...,You are a helpful assistant named Remy whose o...,Vespa plays a crucial role in the Relevance-as...,False,raas,False
1,e860dddb-b6fd-476b-a597-dd598cf571cc,Can you elaborate on how the Two Tower models ...,You are a helpful assistant named Remy whose o...,The Two Tower models are an essential componen...,False,raas,False
2,20a9f467-0235-451c-9f92-d5c6cb526120,What features or interfaces did you build to e...,You are a helpful assistant named Remy whose o...,To empower analysts to create and apply tags e...,False,article tagging,False
3,6a643b4f-8658-4136-896a-1b01420a75dc,What principles or frameworks did you follow w...,You are a helpful assistant named Remy whose o...,The design of system architectures for evaluat...,False,ds-lead,False
4,0f1e6663-eafd-49d9-9002-86005dc8f576,Can you share what code contributions Eric mad...,You are a helpful assistant named Remy whose o...,"In the past 30 days, Eric Washington made the ...",True,raas,True

In [6]:
factual_accuracy_response_lod, successful_response_response_lod = get_auto_annotations(eval_lod, evaluator)

0.0
0.07
0.14
0.21
0.28
0.35
0.43
0.5
0.57
0.64
0.71
0.78
0.85
0.92
0.99

In [11]:
response_lods = [factual_accuracy_response_lod, successful_response_response_lod]
eval_results_df = create_eval_results_df(response_lods)

In [10]:
eval_results_df.groupby(["eval_name", "response"])["thread_id"].count().reset_index()

           eval_name response  thread_id
0  complete_response     fail         14
1  complete_response     pass        127
2   factual_accuracy     fail         17
3   factual_accuracy     pass        124